import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { log } from "@/lib/logger";
import {
  loadShopCredentials,
  upsertShopOAuth,
  type ShopCredentials,
} from "@/server/tenant/shop";
import { normalizeShopId } from "@/server/tenant/id";

/**
 * Minimal Shopify install/auth helpers for a Custom Distribution App.
 *
 * Flow:
 *   1. Merchant clicks the install link generated by Shopify in the Partner
 *      Dashboard (`https://<shop>/admin/oauth/install_custom_app?...`).
 *   2. Shopify shows the consent screen, then redirects to our callback URL
 *      configured in the Partner Dashboard ("Allowed redirection URLs").
 *   3. We verify the HMAC, POST the code to /admin/oauth/access_token,
 *      receive the offline access token, persist to `shops/{shopId}`.
 *   4. Subsequent API calls read credentials from the shop doc.
 */

export function isValidShopDomain(shop: string | null | undefined): boolean {
  if (!shop) return false;
  return /^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(shop.trim());
}

export function getAppCreds(): { apiKey: string; apiSecret: string } {
  const apiKey = process.env.SHOPIFY_API_KEY;
  const apiSecret = process.env.SHOPIFY_API_SECRET;
  if (!apiKey || !apiSecret) {
    throw new Error(
      "SHOPIFY_API_KEY and SHOPIFY_API_SECRET must be set in env",
    );
  }
  return { apiKey, apiSecret };
}

export function verifyInstallHmac(
  params: URLSearchParams,
  apiSecret: string,
): boolean {
  const provided = params.get("hmac");
  if (!provided) return false;
  const entries: [string, string][] = [];
  for (const [k, v] of params.entries()) {
    if (k === "hmac" || k === "signature") continue;
    entries.push([k, v]);
  }
  entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const message = entries.map(([k, v]) => `${k}=${v}`).join("&");
  const expected = createHmac("sha256", apiSecret)
    .update(message, "utf8")
    .digest("hex");
  try {
    const a = Buffer.from(expected, "hex");
    const b = Buffer.from(provided, "hex");
    if (a.length !== b.length) return false;
    return timingSafeEqual(a, b);
  } catch {
    return false;
  }
}

export async function exchangeCodeForToken(
  shop: string,
  code: string,
): Promise<{ accessToken: string; scope: string }> {
  const { apiKey, apiSecret } = getAppCreds();
  const res = await fetch(`https://${shop}/admin/oauth/access_token`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({
      client_id: apiKey,
      client_secret: apiSecret,
      code,
    }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(
      `Shopify token exchange failed: ${res.status} ${text.slice(0, 200)}`,
    );
  }
  const data = (await res.json()) as {
    access_token?: string;
    scope?: string;
  };
  if (!data.access_token) {
    throw new Error("Shopify token exchange returned no access_token");
  }
  return { accessToken: data.access_token, scope: data.scope ?? "" };
}

export type StoredToken = ShopCredentials;

const tokenCache = new Map<
  string,
  { token: StoredToken; loadedAtMs: number }
>();
const TOKEN_CACHE_TTL_MS = 60_000;

export async function loadStoredToken(
  shopId?: string,
): Promise<StoredToken | null> {
  const id = shopId ? normalizeShopId(shopId) : null;
  if (!id) return null;

  const cached = tokenCache.get(id);
  if (cached && Date.now() - cached.loadedAtMs < TOKEN_CACHE_TTL_MS) {
    return cached.token;
  }

  const token = await loadShopCredentials(id);
  if (!token) {
    tokenCache.delete(id);
    return null;
  }
  tokenCache.set(id, { token, loadedAtMs: Date.now() });
  return token;
}

export function invalidateTokenCache(shopId?: string): void {
  if (shopId) tokenCache.delete(normalizeShopId(shopId));
  else tokenCache.clear();
}

export async function persistToken(
  shopDomain: string,
  accessToken: string,
  scope: string,
): Promise<string> {
  const shopId = await upsertShopOAuth(shopDomain, accessToken, scope);
  invalidateTokenCache(shopId);
  log.info("shopify_token_persisted", { shopId: shopId, scope });
  return shopId;
}
