import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { log } from "@/lib/logger";
import {
  upsertShopOAuth,
  type ShopCredentials,
  type ShopOAuthTokenBundle,
} from "@/server/tenant/shop";
import { ensureValidShopCredentials } from "./token";

/**
 * Minimal Shopify install/auth helpers for a Custom Distribution App.
 *
 * Flow:
 *   1. Merchant clicks the install link generated by Shopify in the Partner
 *      Dashboard (`https://<shop>/admin/oauth/install_custom_app?...`).
 *   2. Shopify shows the consent screen, then redirects to our callback URL
 *      configured in the Partner Dashboard ("Allowed redirection URLs").
 *   3. We verify the HMAC, POST the code to /admin/oauth/access_token with
 *      `expiring=1`, receive an offline access + refresh token pair, persist
 *      to `shops/{shopId}`.
 *   4. Subsequent API calls migrate legacy tokens, refresh when needed, then
 *      read credentials from the shop doc.
 */

export function isValidShopDomain(shop: string | null | undefined): boolean {
  if (!shop) return false;
  return /^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(shop.trim());
}

export function getAppCreds(): { apiKey: string; apiSecret: string } {
  const apiKey = process.env.SHOPIFY_API_KEY;
  const apiSecret = process.env.SHOPIFY_API_SECRET;
  if (!apiKey || !apiSecret) {
    throw new Error(
      "SHOPIFY_API_KEY and SHOPIFY_API_SECRET must be set in env",
    );
  }
  return { apiKey, apiSecret };
}

export function verifyInstallHmac(
  params: URLSearchParams,
  apiSecret: string,
): boolean {
  const provided = params.get("hmac");
  if (!provided) return false;
  const entries: [string, string][] = [];
  for (const [k, v] of params.entries()) {
    if (k === "hmac" || k === "signature") continue;
    entries.push([k, v]);
  }
  entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const message = entries.map(([k, v]) => `${k}=${v}`).join("&");
  const expected = createHmac("sha256", apiSecret)
    .update(message, "utf8")
    .digest("hex");
  try {
    const a = Buffer.from(expected, "hex");
    const b = Buffer.from(provided, "hex");
    if (a.length !== b.length) return false;
    return timingSafeEqual(a, b);
  } catch {
    return false;
  }
}

export type StoredToken = ShopCredentials;

export async function loadStoredToken(
  shopId?: string,
): Promise<StoredToken | null> {
  return ensureValidShopCredentials(shopId);
}

export async function persistToken(
  shopDomain: string,
  tokens: ShopOAuthTokenBundle,
): Promise<string> {
  const shopId = await upsertShopOAuth(shopDomain, tokens);
  const { invalidateShopTokenCache } = await import("./token");
  invalidateShopTokenCache(shopId);
  log.info("shopify_token_persisted", { shopId: shopId, scope: tokens.scope });
  return shopId;
}

export type { ShopOAuthTokenBundle };
