import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";
import { FieldValue } from "firebase-admin/firestore";
import { adminDb } from "@/server/firestore/admin";
import { Collections } from "@/server/firestore/schema";
import { log } from "@/lib/logger";

/**
 * Minimal Shopify install/auth helpers for a Custom Distribution App.
 *
 * Flow:
 *   1. Merchant clicks the install link generated by Shopify in the Partner
 *      Dashboard (`https://<shop>/admin/oauth/install_custom_app?...`).
 *   2. Shopify shows the consent screen, then redirects to our callback URL
 *      configured in the Partner Dashboard ("Allowed redirection URLs").
 *      Query: ?code=…&shop=…&hmac=…&host=…&timestamp=…
 *   3. We verify the HMAC, POST the code to /admin/oauth/access_token,
 *      receive the offline access token, persist to Firestore.
 *   4. Subsequent API calls read the token from `config/shopify_token`.
 */

export function isValidShopDomain(shop: string | null | undefined): boolean {
  if (!shop) return false;
  return /^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(shop.trim());
}

export function getAppCreds(): { apiKey: string; apiSecret: string } {
  const apiKey = process.env.SHOPIFY_API_KEY;
  const apiSecret = process.env.SHOPIFY_API_SECRET;
  if (!apiKey || !apiSecret) {
    throw new Error(
      "SHOPIFY_API_KEY and SHOPIFY_API_SECRET must be set in env",
    );
  }
  return { apiKey, apiSecret };
}

/**
 * Verify the query-string HMAC Shopify attaches to install / callback redirects.
 * Format: sorted key=value pairs joined by `&`, signed with client secret as
 * HMAC-SHA256 hex.
 */
export function verifyInstallHmac(
  params: URLSearchParams,
  apiSecret: string,
): boolean {
  const provided = params.get("hmac");
  if (!provided) return false;
  const entries: [string, string][] = [];
  for (const [k, v] of params.entries()) {
    if (k === "hmac" || k === "signature") continue;
    entries.push([k, v]);
  }
  entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const message = entries.map(([k, v]) => `${k}=${v}`).join("&");
  const expected = createHmac("sha256", apiSecret)
    .update(message, "utf8")
    .digest("hex");
  try {
    const a = Buffer.from(expected, "hex");
    const b = Buffer.from(provided, "hex");
    if (a.length !== b.length) return false;
    return timingSafeEqual(a, b);
  } catch {
    return false;
  }
}

export async function exchangeCodeForToken(
  shop: string,
  code: string,
): Promise<{ accessToken: string; scope: string }> {
  const { apiKey, apiSecret } = getAppCreds();
  const res = await fetch(`https://${shop}/admin/oauth/access_token`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({
      client_id: apiKey,
      client_secret: apiSecret,
      code,
    }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(
      `Shopify token exchange failed: ${res.status} ${text.slice(0, 200)}`,
    );
  }
  const data = (await res.json()) as {
    access_token?: string;
    scope?: string;
  };
  if (!data.access_token) {
    throw new Error("Shopify token exchange returned no access_token");
  }
  return { accessToken: data.access_token, scope: data.scope ?? "" };
}

const TOKEN_DOC_ID = "shopify_token";

export type StoredToken = {
  shop_domain: string;
  access_token: string;
  scope: string;
};

let cachedToken: { token: StoredToken; loadedAtMs: number } | null = null;
const TOKEN_CACHE_TTL_MS = 60_000;

export async function loadStoredToken(): Promise<StoredToken | null> {
  if (cachedToken && Date.now() - cachedToken.loadedAtMs < TOKEN_CACHE_TTL_MS) {
    return cachedToken.token;
  }
  const snap = await adminDb()
    .collection(Collections.Config)
    .doc(TOKEN_DOC_ID)
    .get();
  if (!snap.exists) {
    cachedToken = null;
    return null;
  }
  const d = snap.data() ?? {};
  const token: StoredToken = {
    shop_domain: (d.shop_domain as string | undefined) ?? "",
    access_token: (d.access_token as string | undefined) ?? "",
    scope: (d.scope as string | undefined) ?? "",
  };
  if (!token.shop_domain || !token.access_token) return null;
  cachedToken = { token, loadedAtMs: Date.now() };
  return token;
}

export function invalidateTokenCache(): void {
  cachedToken = null;
}

export async function persistToken(
  shopDomain: string,
  accessToken: string,
  scope: string,
): Promise<void> {
  await adminDb()
    .collection(Collections.Config)
    .doc(TOKEN_DOC_ID)
    .set(
      {
        shop_domain: shopDomain,
        access_token: accessToken,
        scope,
        installed_at: FieldValue.serverTimestamp(),
      },
      { merge: false },
    );
  invalidateTokenCache();
  log.info("shopify_token_persisted", { shopDomain, scope });
}
